# Generated by Django 5.2.1 on 2025-05-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodtracker',
            name='user',
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
