# Generated by Django 5.2.1 on 2025-05-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_moodtracker_user_moodtracker_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodtracker',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
