# Generated by Django 5.2.1 on 2025-05-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akalya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='mobile_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
